package alice.af;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(
	modid = "advfiller",
	name = "Advanced Filler",
	version = "0.1",
	dependencies = "required-after:Forge@[10.13.2.1291,);after:BuildCraft|Core"
)
public final class AdvancedFiller
{
	@Mod.Instance("advfiller")
	public static AdvancedFiller INSTANCE;

	@Mod.Metadata("advfiller")
	private ModMetadata meta;

	@SidedProxy(clientSide = "alice.af.client.ClientProxy", serverSide = "alice.af.Proxy")
	public static Proxy PROXY;

	@Mod.EventHandler
	public void forgePreInitialization(FMLPreInitializationEvent event)
	{
		this.setupMetadata();
		AdvancedFiller.PROXY.forgePreInitialization(event);
	}

	private void setupMetadata()
	{
		this.meta.description = "昔ながらのシンプルなフィラーを強化しました。\nOriginal:@firstspring1845, @7sr_";
		this.meta.url = "http://a1lic.net/";
		this.meta.authorList.add("alice");
		this.meta.credits = "alice";
		// falseにしないとMod listで情報が出ない。
		this.meta.autogenerated = false;
	}

	@Mod.EventHandler
	public void forgeInitialization(FMLInitializationEvent event)
	{
		AdvancedFiller.PROXY.forgeInitialization(event);
	}

	@Mod.EventHandler
	public void forgePostInitialization(FMLPostInitializationEvent event)
	{
		AdvancedFiller.PROXY.forgePostInitialization(event);
	}
}
